jenkins:
  systemMessage: |
    -------------------  Jenkins -------------------
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
      standard:
          excludeClientIPFromCrumb: true
  numExecutors: 2
  securityRealm:
    ldap:
      configurations:
        - groupMembershipStrategy:
            fromUserRecord:
              attributeName: " "
          server: "ldaps://laas.bmwgroup.net:6362"
          rootDN: "dc=bmwgroup,dc=com"
          userSearchBase: ""
          userSearch: "uid={0}"
          managerDN: "uid=QQVNS00,ou=people,dc=bmwgroup,dc=com"
          managerPasswordSecret: "0bl1x432"
          displayNameAttributeName: "cn"
          mailAddressAttributeName: "mail"
